### ISSUE TITLE
Get data of a form

### ISSUE THREAD

**Issue by WebbYang** [IBM/tririga-api#2]
Hi,
I would like to get the form fields of Energy Use from an existing building using api.
Is there an example api to get the data like "triEnvElectricityEmissionData"?
What IDs are going to be inside the query? 

Thank you

**Comment by sumitpuri** [comment]
Any field from the triBuilding BO can be added in the OSLC API. 

Navigate to System Reports > `triAPICBuilding - OSLC - Properties` and add the required fields to the query and then click `Import Fields` on the `triAPICBuildingRS` OSLC Resource. This would pull in the custom fields as well.

<img width="1132" alt="image" src="https://github.com/IBM/tririga-api/assets/6925028/680ce1b2-8d20-46da-9482-0f84acb79ce4">
